- profile/static/css/main.css
- profile/templates/exops/is-exops-user-applications.html
[this task](https://uktrade.atlassian.net/browse/ED-1184)
> Implement design of ex ops tab

- profile/static/css/main.css
- profile/templates/exops/opportunities-retrieve-error.html
- profile/templates/fab/supplier-company-retrieve-error.html
[this task](https://uktrade.atlassian.net/browse/ED-1178)
> Show error message on fab down

- profile/static/css/main.css
- profile/templates/landing-page.html
[simplified version of this task](https://uktrade.atlassian.net/browse/ED-1175)
> Add generic welcome information about the app

- profile/static/javascripts/index.js
- profile/templates/base.html
- profile/templates/google_tag_manager_body.html
- profile/templates/google_tag_manager_head.html
all copied and pasted from FAB
> Add google tag manager integration

- profile/static/css/main.css
[this task](https://uktrade.atlassian.net/browse/ED-1196)
> Improve style of exops view

- profile/static/css/main.css
- profile/templates/fab/is-fab-user.html
[this task](https://uktrade.atlassian.net/browse/ED-1196)
> Improve style of fab view on mobile

- profile/eig_apps/tests/test_views.py
- profile/static/css/main.css
- profile/templates/apps-tabs.html
> Hide extra logout button from the profile bar

- requirements.txt
[this task](https://uktrade.atlassian.net/browse/ED-201)
> Add signature auth library to dependencies

- profile/static/javascripts/index.js
UTM param issue on SSO-Profile
> ED-1262 Fix loop on null when regex fails to return result

- makefile
[this task](https://uktrade.atlassian.net/browse/ED-1557)
> Update the link for creating company

- profile/templates/exops/is-not-exops-user.html
- profile/templates/landing-page.html
Change “Our” tools to “The” tools
Change "1000s" to "thousands"
> ED-1683 Update content

- profile/templates/selling-online-overseas.html
[this task](https://uktrade.atlassian.net/browse/ED-1721)
The url changed on their end.
> Fix SOO link

- profile/api/helpers.py
- profile/api/tests/test_helpers.py
- profile/api/tests/test_views.py
- profile/api/views.py
Re-adding functionality removed by [this PR](https://github.com/uktrade/directory-sso-profile/pull/59)
> Re-add bearer token

- profile/exops/tests/test_templates.py
- profile/templates/exops/is-exops-user-email-alerts.html
[this task](https://uktrade.atlassian.net/browse/ED-1371)
> Handle empty search term

- config/middleware.py
- config/settings.py
- config/tests/test_middlware.py
[this task](ED-1245-cache-headers)
> Add no-cache middleware

- .codeclimate.yml
- conftest.py
- sso/middleware.py
- sso/tests/test_middleware.py
[this task](https://uktrade.atlassian.net/browse/ED-2114)
> Add helpful error on bad SSO response

- profile/api/tests/test_views.py
- profile/api/views.py
- profile/fab/helpers.py
- profile/fab/tests/test_templates.py
- profile/fab/tests/test_views.py
- profile/fab/views.py
- profile/templates/fab/is-fab-user.html
- requirements.txt
[this task](https://uktrade.atlassian.net/browse/ED-2171)
> Prevent display of multi user management links if not profile owner

- profile/fab/tests/test_views.py
- profile/fab/views.py
- profile/static/css/main.css
- profile/templates/fab/is-fab-user.html
- profile/templates/fab/is-not-fab-user.html
[this task](https://uktrade.atlassian.net/browse/ED-2187)
> Show success message on multi user change

- profile/static/css/main.css
[this task](https://uktrade.atlassian.net/browse/ED-2148)
> Use GDS green for alert banner

- profile/fab/views.py
https://uktrade.atlassian.net/browse/ED-2318
> Success messages added

- profile/templates/base.html
[this task](https://uktrade.atlassian.net/browse/ED-2556)
> Upgrade jquery for browsers that support it

- config/settings.py
- makefile
- profile/static/css/main.css
- requirements.in
- requirements.txt
- requirements_test.txt
https://uktrade.atlassian.net/browse/ED-2535
> Update header/footer 

- profile/static/css/main.css
- profile/templates/404.html
[this task](https://uktrade.atlassian.net/browse/ED-2839)
> Addd styled 4040 page

- profile/static/css/main.css
- requirements.in
- requirements.txt
- requirements_test.txt
https://uktrade.atlassian.net/browse/ED-2867
> Ed 2867 upgrade header footer

- profile/static/css/main.css
[this task](https://uktrade.atlassian.net/browse/ED-2907)
> Add missing styles previously provided by old header

- config/settings.py
- config/urls.py
- docker/env.json
- docker/env.test.json
- healthcheck/backends.py
- healthcheck/tests/test_backends.py
- healthcheck/tests/test_views.py
- healthcheck/views.py
- makefile
- requirements.in
- requirements.txt
- requirements_test.txt
[this task](https://uktrade.atlassian.net/browse/ED-2933)
> Add helthcheck views

- config/settings.py
[this task](https://uktrade.atlassian.net/browse/ED-3050)
> Add APPEND_SLASH

- requirements.in
- requirements.txt
- requirements_test.txt
https://uktrade.atlassian.net/browse/ED-4097
> Upgrade components to fix duplicate heading in footer

- profile/templates/about.html
- profile/templates/fab/is-not-fab-user.html
[this task](https://uktrade.atlassian.net/browse/TT-99)
> Trade to business profile

- requirements.txt
- requirements_test.txt
- sso/middleware.py
- sso/tests/test_middleware.py
[this task](https://uktrade.atlassian.net/browse/TT-221)
> handle timeout of sso

- requirements.in
- requirements.txt
- requirements_test.txt
https://uktrade.atlassian.net/browse/CMS-148
> Add cookie notice

- conf/settings.py
- makefile
- profile/exops/tests/test_templates.py
- profile/templates/exops/is-exops-user-email-alerts.html
[this task](https://uktrade.atlassian.net/browse/TT-263)
> Improve display of exopps email alerts

- conf/settings.py
- docker/env.json
- docker/env.test.json
- makefile
- requirements.in
- requirements.txt
- requirements_test.txt
[this task](https://uktrade.atlassian.net/browse/TT-301)
> Facilitate setting shared cookie

- profile/templates/about.html
[this task](https://uktrade.atlassian.net/browse/TT-310)
> Replace erroneous account with profile

- .gitignore
- conf/settings.py
- makefile
> Remove DRF API UI renderer

- .circleci/config.yml
- Dockerfile
- conf/urls.py
- healthcheck/backends.py
- healthcheck/tests/test_backends.py
- healthcheck/tests/test_views.py
- healthcheck/views.py
- requirements.in
- requirements.txt
- requirements_test.txt
- runtime.txt
[this task](https://uktrade.atlassian.net/browse/TT-533)
> Add sentry healthcheck

- conf/settings.py
- conf/urls.py
- healthcheck/tests/test_views.py
- profile/api/tests/test_views.py
- requirements.in
- requirements.txt
- requirements_test.txt
[this task](https://uktrade.atlassian.net/browse/TT-768)
> Add IP restriction capability

- enrolment/forms.py
- enrolment/templates/enrolment/companies-house-search.html
- enrolment/tests/test_forms.py
[this task](https://uktrade.atlassian.net/browse/TT-924)
> Show error on not selecting a company from companies house search

- runtime.txt
To make python version the same across all apps
> change python version to be consistent.

- enrolment/forms.py
- enrolment/templates/enrolment/business-type.html
Updating H1 to "Select your business type"
> Business type page updates

- enrolment/templates/enrolment/companies-house-business-details.html
- enrolment/templates/enrolment/companies-house-search.html
- enrolment/templates/enrolment/sole-trader-business-details.html
- enrolment/templates/enrolment/sole-trader-search.html
Updating business details page
> Updating business details page

- enrolment/templates/enrolment/companies-house-business-details.html
- enrolment/templates/enrolment/companies-house-personal-details.html
- enrolment/templates/enrolment/companies-house-search.html
- enrolment/templates/enrolment/companies-house-sole-trader.html
- enrolment/templates/enrolment/sole-trader-business-details.html
- enrolment/templates/enrolment/sole-trader-personal-details.html
- enrolment/templates/enrolment/sole-trader-search.html
> Removing "organisation"

- enrolment/templates/enrolment/user-account-verification.html
Updating content on the verification page
> Updating content on the verification page

- conf/urls.py
- enrolment/helpers.py
- enrolment/templates/enrolment/failure-pre-verified.html
- enrolment/templates/enrolment/preverified-personal-details.html
- enrolment/templates/enrolment/success-pre-verified.html
- enrolment/tests/test_views.py
- enrolment/views.py
- requirements.in
- requirements.txt
- requirements_test.txt
[part of this](https://uktrade.atlassian.net/browse/TT-1022)
This enrolment flow will handle the case when the users are given the urls generated by the admin bulk company create
> Support pre-verified enrolment

- enrolment/templates/enrolment/companies-house-personal-details.html
[this task](https://uktrade.atlassian.net/browse/TT-1093)
> Companies house enrolment change company

- enrolment/templates/enrolment/sole-trader-business-details.html
[this task](https://uktrade.atlassian.net/browse/TT-1090)
> Fix sole trader label

- enrolment/templates/enrolment/companies-house-personal-details.html
- enrolment/templates/enrolment/preverified-personal-details.html
- enrolment/templates/enrolment/sole-trader-personal-details.html
[this task](https://uktrade.atlassian.net/browse/TT-1162)
> Remove link to list of background checks

- profile/templates/about.html
[this task](https://uktrade.atlassian.net/browse/TT-1147)
> Make about page more inclusive of UKAN

- enrolment/templates/enrolment/success-companies-house.html
[this task](https://uktrade.atlassian.net/browse/TT-1000)
> Update CH success page

- enrolment/forms.py
- enrolment/helpers.py
- enrolment/tests/test_forms.py
- enrolment/tests/test_views.py
- enrolment/views.py
[this task](https://uktrade.atlassian.net/browse/TT-1189)
> Prevent enrolling non-active companies

- enrolment/templates/enrolment/success-pre-verified.html
- enrolment/templates/enrolment/success-sole-trader.html
[this task](https://uktrade.atlassian.net/browse/TT-1203)
> Improve success page of ISD enrolmnet and sole trader

- profile/templates/fab/find-a-buyer-publsh.html
[this task](https://uktrade.atlassian.net/browse/TT-1231)
> Improve content on publish page

- enrolment/forms.py
- enrolment/tests/test_views.py
- enrolment/views.py
[this task](https://uktrade.atlassian.net/browse/TT-1249)
> Make sectors work on enrolment

- profile/eig_apps/tests/test_views.py
- profile/eig_apps/views.py
- profile/exops/tests/test_views.py
- profile/exops/views.py
- profile/fab/tests/test_views.py
- profile/fab/views.py
- profile/soo/tests/test_views.py
- profile/soo/views.py
[this task](https://uktrade.atlassian.net/browse/TT-1240)
> Remove redirect to about page

- profile/fab/helpers.py
- profile/fab/tests/test_helpers.py
[this task](https://uktrade.atlassian.net/browse/TT-1245)
> Fix display of keywords

- profile/fab/views.py
[this task](https://uktrade.atlassian.net/browse/TT-1282)
> Fix case study image upload

- profile/templates/fab/expertise-countries-form.html
[this task](https://uktrade.atlassian.net/browse/TT-1312)
> Fix countries label

- CHANGELOG.md
- core/static/js/products-services.js
- profile/templates/fab/products-services-form.html
[this task](https://uktrade.atlassian.net/browse/TT-1271)
> Show products services dropdown arrow

- CHANGELOG.md
- conf/urls.py
- profile/fab/forms.py
- profile/fab/tests/test_views.py
- profile/fab/views.py
- profile/templates/fab/products-services-form.html
- profile/templates/fab/products-services-other-form.html
- profile/templates/fab/products-services-routing-form.html
- profile/templates/fab/profile.html
- requirements.in
[this task](https://uktrade.atlassian.net/browse/TT-1271)
[this task](https://uktrade.atlassian.net/browse/TT-1415)
[this task](https://uktrade.atlassian.net/browse/TT-1426)
> Allow free text entry of other

- CHANGELOG.md
- profile/fab/forms.py
- profile/templates/fab/products-services-other-form.html
[this task](https://uktrade.atlassian.net/browse/TT-1423)
> Improve content of other products and services for ISD

- CHANGELOG.md
- conf/urls.py
- core/tests/helpers.py
- enrolment/templates/enrolment/overseas-business.html
- enrolment/tests/test_views.py
- enrolment/views.py
- profile/fab/tests/test_views.py
> Handle oversreas business enrolment

- CHANGELOG.md
- core/templates/core/wizard.html
- enrolment/templates/enrolment/failure-pre-verified.html
- enrolment/templates/enrolment/overseas-business.html
- enrolment/templates/enrolment/start.html
- enrolment/templates/enrolment/wizard.html
- profile/templates/apps-tabs.html
> Show banner prompting business profile creation

- conf/urls.py
- enrolment/templates/enrolment/individual-interstitial.html
- enrolment/tests/test_views.py
- enrolment/views.py
> Show intersticial for individual enrolment

- CHANGELOG.md
- core/templates/core/wizard.html
- enrolment/templates/enrolment/individual-interstitial.html
- enrolment/templates/enrolment/overseas-business.html
- enrolment/templates/enrolment/start.html
- enrolment/tests/test_views.py
- enrolment/views.py
- profile/templates/fab/is-not-fab-user.html
> Show different enrolment title depending on user journey

- .circleci/config.yml
- CHANGELOG.md
- enrolment/forms.py
- enrolment/views.py
- makefile
- profile/fab/forms.py
- profile/fab/tests/test_views.py
> TT-1639 added please select to lists

- core/static/js/expertise.js
- core/static/js/products-services.js
- profile/fab/forms.py
- profile/templates/fab/products-services-form.html
> Placeholder for typeaheads

- CHANGELOG.md
- conf/urls.py
- enrolment/templates/enrolment/companies-house-success.html
- enrolment/templates/enrolment/individual-personal-details.html
- enrolment/templates/enrolment/information_box_companies_type.html
- requirements.in
- requirements.txt
- requirements_test.txt
> Fix incorrect label displaying for non companies house company

- CHANGELOG.md
- enrolment/templates/enrolment/non-companies-house-business-details.html
> Fixing persistant error message on UI

- enrolment/templates/enrolment/information_box_companies_type.html
Added option {% else %}  for sole trader
changed limited company option
changed UK taxpayer option
changed not in the uk option
> reg journey content update: select business type

- CHANGELOG.md
- profile/templates/apps-tabs.html
Gave context to content of banner telling user to complete their Business Profile
> Complete profile banner content update

- CHANGELOG.md
- conf/urls.py
- profile/fab/forms.py
- profile/fab/helpers.py
- profile/fab/tests/test_views.py
- profile/fab/views.py
- profile/templates/fab/admin-collaborator-edit.html
- profile/templates/fab/admin-collaborator-list.html
- requirements_test.txt
> Support removing collaborators

- CHANGELOG.md
- enrolment/views.py
- profile/templates/fab/profile.html
> TT-1709 content changes

- CHANGELOG.md
- conf/urls.py
- enrolment/tests/test_views.py
- enrolment/views.py
- profile/fab/forms.py
- profile/fab/helpers.py
- profile/fab/tests/test_views.py
- profile/fab/views.py
- profile/templates/fab/admin-base.html
- profile/templates/fab/admin-invite-collaborator.html
> Allow inviting collaborator

- conf/urls.py
- enrolment/helpers.py
- enrolment/tests/test_helpers.py
- enrolment/tests/test_views.py
- enrolment/views.py
- profile/fab/forms.py
- profile/fab/helpers.py
- profile/fab/tests/test_helpers.py
- profile/fab/tests/test_views.py
- profile/fab/views.py
- profile/templates/fab/admin-base.html
- profile/templates/fab/admin-collaborator-edit.html
- profile/templates/fab/admin-disconnect.html
- profile/templates/fab/admin-invite-admin.html
- profile/templates/fab/admin-invite-collaborator.html
- profile/templates/fab/find-a-buyer-publsh.html
- requirements.in
- requirements.txt
- requirements_test.txt
> Make collaboration work end to end

- CHANGELOG.md
- conf/urls.py
- enrolment/forms.py
- enrolment/helpers.py
- enrolment/tests/test_forms.py
- enrolment/tests/test_helpers.py
- enrolment/tests/test_views.py
- enrolment/views.py
- requirements.in
> Collaboration invitee journey

- CHANGELOG.md
- makefile
- requirements_test.in
- requirements_test.txt
- sso/models.py
- sso/tests/test_models.py
> Handle user has no supplier on profile page

- CHANGELOG.md
- conf/urls.py
- conftest.py
- core/mixins.py
- enrolment/views.py
- profile/business_profile/tests/test_views.py
- profile/business_profile/views.py
- profile/personal_profile/forms.py
- profile/personal_profile/tests/test_views.py
- profile/personal_profile/views.py
- profile/templates/personal_profile/personal-profile.html
> Tt 1812  save profile error

- CHANGELOG.md
- conf/urls.py
- enrolment/templates/enrolment/individual-interstitial.html
> No longer prompt users with profiles to create a profile

- .circleci/config.yml
- .flake8
- CHANGELOG.md
- enrolment/templates/enrolment/individual-collaborator-invite-expired.html
- enrolment/templates/enrolment/individual-success.html
- enrolment/tests/test_views.py
- enrolment/views.py
- makefile
- pytest.ini
> Show message for expired links

- CHANGELOG.md
- profile/business_profile/views.py
> fix new admin email display

- enrolment/templates/enrolment/address-search.html
> Fix address lookup

- CHANGELOG.md
- enrolment/templates/enrolment/start.html
> TT-1786 change txt

- CHANGELOG.md
- enrolment/templates/enrolment/companies-house-search.html
> Tt 1853 404 guidance page - Hotifix

- CHANGELOG.md
- profile/templates/business_profile/admin-base.html
> TT-1807 - hide-profile-tab

- CHANGELOG.md
- profile/business_profile/helpers.py
> TT-1857 fix is in companies-house

- CHANGELOG.md
- enrolment/templates/enrolment/companies-house-business-details.html
> TT-1856 fix persistent is enrolled message 

- CHANGELOG.md
- enrolment/templates/enrolment/base.html
- enrolment/templates/enrolment/wizard.html
- profile/templates/business_profile/admin-base.html
- profile/templates/business_profile/base.html
> TT-1797 - fix page-titles

- CHANGELOG.md
- conftest.py
- core/helpers.py
- core/tests/test_helpers.py
- profile/business_profile/tests/test_views.py
- profile/business_profile/views.py
- profile/templates/business_profile/admin-invite-collaborator.html
- profile/templates/business_profile/profile.html
> Tt 1904 ui bugs

- CHANGELOG.md
- enrolment/forms.py
> Reinstate missing terms tickbox

- CHANGELOG.md
- core/helpers.py
- core/tests/test_helpers.py
> Fix update profile error if user has no supplier

- CHANGELOG.md
- enrolment/views.py
- profile/business_profile/forms.py
- profile/business_profile/tests/test_views.py
- profile/business_profile/views.py
> Tt 1946 remove editor options

- CHANGELOG.md
- enrolment/mixins.py
- enrolment/tests/test_views.py
- enrolment/views.py
> Tt 1942 wizard finish redirects v2

- CHANGELOG.md
- profile/templates/business_profile/admin-base.html
- profile/templates/business_profile/admin-collaborator-edit.html
- profile/templates/business_profile/admin-collaborator-list.html
- profile/templates/business_profile/admin-disconnect.html
- profile/templates/business_profile/admin-invite-admin.html
- profile/templates/business_profile/admin-invite-collaborator.html
- profile/templates/business_profile/admin-tools.html
> TT-2038 fix breadcrumbs

- CHANGELOG.md
- enrolment/fields.py
- enrolment/forms.py
> Use correct input types for number fields

- CHANGELOG.md
- enrolment/forms.py
- requirements.in
- requirements.txt
- requirements_test.txt
> Fixing address preview field size

- CHANGELOG.md
- profile/templates/personal_profile/personal-profile.html
> Fix padding on success box

- CHANGELOG.md
- enrolment/constants.py
> Handle companies starting with CE

- CHANGELOG.md
- conf/settings.py
> Set message storage backend

- CHANGELOG.md
- enrolment/mixins.py
- enrolment/templates/enrolment/companies-house-success.html
- enrolment/templates/enrolment/individual-success.html
- enrolment/templates/enrolment/non-companies-house-success.html
- enrolment/tests/test_views.py
- enrolment/views.py
- profile/templates/business_profile/admin-base.html
- profile/templates/business_profile/admin-collaborator-list.html
- profile/templates/business_profile/profile.html
- pytest.ini
> Do not show we will contact you if already verified

- CHANGELOG.md
- enrolment/forms.py
- enrolment/tests/test_forms.py
> TT-2089 fix code input

- CHANGELOG.md
- enrolment/templates/enrolment/collaborator-personal-details.html
- enrolment/views.py
> Not prompt collaborators to change business type

- CHANGELOG.md
- enrolment/templates/enrolment/individual-interstitial.html
> Fix layout problem on enrolment of individual that already has sso profile

- enrolment/forms.py
- enrolment/tests/test_forms.py
> Handle companies with no company status

- CHANGELOG.md
- enrolment/mixins.py
- enrolment/templates/enrolment/companies-house-success.html
- enrolment/templates/enrolment/individual-success.html
- enrolment/templates/enrolment/non-companies-house-success.html
- enrolment/tests/test_views.py
- enrolment/views.py
> link user to ingress url on success page

- CHANGELOG.md
- enrolment/templates/enrolment/address-search.html
- enrolment/tests/test_views.py
- enrolment/views.py
> Fix incorrect company type label on enrolment

- profile/templates/business_profile/business-details-form.html
> Update business type edit content

- CHANGELOG.md
- enrolment/forms.py
- enrolment/tests/test_forms.py
> TT-2189 confirm password empty 500 error

- CHANGELOG.md
- enrolment/helpers.py
> Remove "is enrolled" caching

- CHANGELOG.md
- conf/settings.py
- profile/business_profile/views.py
- profile/templates/business_profile/admin-collaborator-list.html
- profile/templates/business_profile/business-profile-member.html
> TT2212 - add feature flag

- CHANGELOG.md
- enrolment/tests/test_views.py
- profile/business_profile/tests/test_views.py
- profile/business_profile/views.py
> Fix business profile load for user with no business

- CHANGELOG.md
- core/templates/core/wizard.html
> Diabled in-browser validation

- CHANGELOG.md
- enrolment/helpers.py
- enrolment/tests/test_helpers.py
- enrolment/tests/test_views.py
- enrolment/views.py
- requirements.in
- requirements.txt
- requirements_test.txt
> Handle preverified company multiple users

- CHANGELOG.md
- core/templates/directory_components/base.html
- requirements.in
- requirements.txt
- requirements_test.txt
> cookie change

- CHANGELOG.md
- profile/templates/business_profile/admin-collaborator-edit.html
- profile/templates/business_profile/admin-collaborator-list.html
- profile/templates/business_profile/admin-disconnect.html
- profile/templates/business_profile/admin-invite-admin.html
- profile/templates/business_profile/admin-invite-collaborator.html
- profile/templates/business_profile/base-form.html
- profile/templates/business_profile/business-profile-member.html
- profile/templates/business_profile/business-profile-publish.html
- profile/templates/business_profile/disconnect-from-company.html
- profile/templates/personal_profile/personal-profile-edit-form.html
> Remove in-browser form validation

- profile/templates/business_profile/profile.html
> Improve content on publish profile link

- CHANGELOG.md
- profile/exops/helpers.py
- profile/exops/tests/test_helpers.py
- profile/exops/tests/test_templates.py
- profile/exops/tests/test_views.py
- profile/exops/views.py
- profile/templates/exops/is-exops-user-applications.html
- profile/templates/exops/is-exops-user-email-alerts.html
> Add new changed ExOps API

- CHANGELOG.md
> Release 20 April

- CHANGELOG.md
- profile/templates/business_profile/admin-disconnect.html
- profile/templates/business_profile/profile.html
> Improve confusing content on remove from account button

- CHANGELOG.md
- requirements.in
- requirements.txt
- requirements_test.in
- requirements_test.txt
> Dependencies upgrade

- CHANGELOG.md
- conf/settings.py
- enrolment/forms.py
> GAA-5-upgrade-captcha-v3

- CHANGELOG.md
- profile/templates/business_profile/business-profile-member.html
- requirements.in
- requirements.txt
- requirements_test.txt
> GAA-28 - switch h1s to h2s

- CHANGELOG.md
- requirements.in
- requirements.txt
- requirements_test.txt
> GAA-27 - Bump directory-components version

- CHANGELOG.md
- requirements.in
- requirements.txt
- requirements_test.txt
> GBAU-889 - Fix Cookie modal JS error

- CHANGELOG.md
- requirements.in
- requirements.txt
- requirements_test.txt
> fix-vulnerabilities

- requirements.in
- requirements.txt
- requirements_test.txt
>  fix-vulnerabilities-23-mar-2020-dev

- .circleci/config.yml
- CHANGELOG.md
- README.md
- manifest.yml
- requirements.in
- requirements.txt
- requirements_test.txt
- runtime.txt
> Python 3.9 upgrade

- CHANGELOG.md
- requirements.in
- requirements.txt
- requirements_test.txt
> GP2-2784: Bump directory components

- CHANGELOG.md
- enrolment/views.py
> GBAU-964-incorrect-preverifed-company-status

- CHANGELOG.md
- requirements.in
- requirements.txt
- requirements_test.txt
> staging release 

- CHANGELOG.md
- requirements.in
- requirements.txt
- requirements_test.txt
> PROD release

- CHANGELOG.md
- manifest.yml
- runtime.txt
> Pinned CF buildpack and upgraded python to 3.9.5
